# Generated by Django 2.2.5 on 2019-09-26 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_auto_20190906_1606'),
        ('documentos', '0003_documentos_arquivo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documentos',
            new_name='Documento',
        ),
    ]
